### PR TITLE
Hatchbot inlined

### PR DESCRIPTION
**Pull request by BerkeSinanYetkin**
as per #49

I will rebase the branch after drivedistanceoffboard example is merged

### CODE REVIEW

**Comment by BerkeSinanYetkin** [comment]
I've created a draft pr because there is no need for 2 people to port the same code twice, i'm on it.

**Comment by BerkeSinanYetkin** [comment]
closing in favor of #67

**Comment by auscompgeek** [comment]
I'm confused, why the new PR?

**Comment by BerkeSinanYetkin** [comment]
> I'm confused, why the new PR?

I opened this in hatchbot-inlined branch since there was an ongoing PR for gyro-drive-commands on the main branch of my fork.

https://github.com/robotpy/examples/pull/56#issuecomment-1356883633

@virtuald commented this on one of my previous PRs, if it is unnecessary, please let me know. By now you must have figured out that I'm not the best with git, but I'm trying to learn! 😄

**Pull request closed without merging**
