### PR TITLE
Rewrote CrispyBacon1999's robotopy-examples, excluding the directory changes.

### PR DESCRIPTION
**Pull request by benjiboy50fonz**
**Summary**
Forked the current robotpy-examples, and separated the legitimate fixes from directory changes. This PR consists of the legitimate fixes contributed to robotpy-examples by CrispyBacon1999, and copied over by myself.

### CODE REVIEW

**Comment by virtuald** [comment]
Silly question since we no longer have automated testing: did you try the examples to see if they don't crash?

**Comment by benjiboy50fonz** [comment]
I'm afraid I forgot. Working on that now.

**Comment by virtuald** [comment]
All set?

**Comment by benjiboy50fonz** [comment]
So as of now, the tests are succeeding for most but failing for others. This was through manual testing, as the `robot.py test --builtin` leads to errors after uncommenting fallback @virtuald implemented. Still need to update the ignore tests for the examples that are failing.

**Comment by virtuald** [comment]
Thanks so much!

**Pull request merged**
