### PR TITLE
Frisbeebot example

### PR DESCRIPTION
**Pull request by BerkeSinanYetkin**
extension of #56, as you can't change which branch you want to merge from on a ongoing pr.

### CODE REVIEW

**Comment by BerkeSinanYetkin** [comment]
@virtuald should i add the frisbeebot example to ignored tests? It works as intended in simulation but setDistancePerPulse fails the test even though it seems like nothing has changed from 2022.

**Comment by virtuald** [comment]
Let me take a look locally.

**Comment by virtuald** [comment]
The problem is that all of your motors are initialized at the class level instead of in `__init__`. I'll see if I can make pyfrc give a better error message when that happens.

**Comment by virtuald** [comment]
I'm going to go ahead and fix this locally, adjust some of the style to match python better, and push a new PR using the fixes in a few minutes. Thanks!

**Comment by virtuald** [comment]
Closed in favor of #59

**Pull request closed without merging**
