### PR TITLE
Frisbeebot

### PR DESCRIPTION
**Pull request by BerkeSinanYetkin**
#49 again

seems like wpilib2023 changed a lot of methods' names. Also updated those in the other examples.

### CODE REVIEW

**Comment by BerkeSinanYetkin** [comment]
Do the tests run in 2022 wpilib?

**Comment by BerkeSinanYetkin** [comment]
> Do the tests run in 2022 wpilib?

I believe this might be the problem, the ramsete example doesn't fail on my computer

**Comment by BerkeSinanYetkin** [comment]
Frisbeebot's setDistancePerPulse methods and romi's pyntcore imports fail on my machine. Though Frisbeebot works as intended in simulation. Should I add it to ignored tests? Have no idea why romi doesn't work, can't figure it out.

**Comment by mrguisamuel** [comment]
> Do the tests run in 2022 wpilib?

Hey @BerkeSinanYetkin, did you try to update from 2022 to 2023 beta?
I also have this problem when I converted the armbotoffboard example.

`pip install --pre robotpy`

**Comment by BerkeSinanYetkin** [comment]
> > Do the tests run in 2022 wpilib?
> 
> Hey @BerkeSinanYetkin, have you tried to update from 2022 to 2023 beta? I also had this problem when I converted the armbotoffboard example.
> 
> `pip install --pre robotpy`

I did update to the beta, After I did that and wrote the frisbeebot example; the tests didn't like the other examples, so I changed them to work with 2023 and now the test on github don't approve my changes, but my machine which runs the beta do approve them when i run "run_tests.sh" on my terminal.

driveCartesian's gyro argument and wpilib.SpeedControllerGroup's name have changed to Rotation2d and MotorControllerGroup iirc, there might be other changes too.

**Comment by virtuald** [comment]
Hey, I'm going to fix the 2023-beta branch and merge that into main momentarily. Then you can work off that.

**Comment by virtuald** [comment]
Ok, I've merged the 2023-beta branch into main, and the tests all pass. Please rebase this branch off of the current main, update to the latest beta (robotpy 2023.0.0b7), and all should be well. Sorry for the confusion!

If you're having issues rebasing your branch, then let me know and we can figure something out.

**Comment by BerkeSinanYetkin** [comment]
> Ok, I've merged the 2023-beta branch into main, and the tests all pass. Please rebase this branch off of the current main, update to the latest beta (robotpy 2023.0.0b7), and all should be well. Sorry for the confusion!
> 
> If you're having issues rebasing your branch, then let me know and we can figure something out.

AFAIK you can't change which branch you want to merge from, so i'm closing this pr and creating a new one.

**Comment by virtuald** [comment]
You can force push over your existing branch after you rebase. But sure, whatever works for you.

**Pull request closed without merging**
