### PR TITLE
Add TimedRobot example

### PR DESCRIPTION
**Pull request by twinters007**
I think I copied straight from Iterative

### CODE REVIEW

**Comment by auscompgeek** [comment]
You forgot to add the example to the list.

**Comment by auscompgeek** [comment]
I still don't believe this actually works… does it respond correctly in the sim?

**Comment by twinters007** [comment]
Yeah

**Comment by auscompgeek** [comment]
what is this witchcraft

**Comment by twinters007** [comment]
🤷‍♀️

**Comment by virtuald** [comment]
Might need a rebase?

**Comment by auscompgeek** [comment]
Superseded by #14 (which actually is copied from iterative).

… hm, I don't have write access here. Oh well.

**Pull request closed without merging**
